### ISSUE TITLE
Int.fromStringWithRadix (parseInt) missing

### ISSUE THREAD

**Issue by Minnozz** [bloodyowl/rescript-js#11]
The current binding has a fixed argument for the radix:
https://github.com/bloodyowl/rescript-js/blob/802ef39a804fb998c21c9f8159c0d20cf4385c3f/src/Js__Int.res#L19

**Comment by bloodyowl** [comment]
You have `Float.parseIntWithRadix` for that. The rationale behind putting it there is that it might return `NaN` which belongs to floats.

**Comment by Minnozz** [comment]
I see `Int.fromString` returns an `option<int>`; would that be an option for `Int.fromStringWithRadix`?

**Comment by bloodyowl** [comment]
I guess having a slight runtime on this wouldn't hurt given how often people can use it. Would you be able to send a PR?
