### ISSUE TITLE
Typed arrays are incorrectly capitalized on the JS side

### ISSUE THREAD

**Issue by Minnozz** [bloodyowl/rescript-js#2]
E.g. `UInt8Array` should be `Uint8Array` with lowercase `i`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array

The current bindings give this error:
```
Uncaught ReferenceError: UInt8Array is not defined
```

I'm not sure whether the ReScript side should be changed too, what do you think?

**Comment by Minnozz** [comment]
Nevermind @ the ReScript side comment; the capitalization is already correct there. I've made a PR that fixes the bindings.

**Comment by bloodyowl** [comment]
Thanks for your fix, released in v0.5.2
